# Generated by Django 2.0.7 on 2018-07-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('capacity', models.IntegerField()),
                ('building', models.CharField(max_length=150)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
